# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0549da97450cfcfe08c354d41db558f210810c3f085e27fb03627f334ac6637132d6290a840d4b3dc3b0bcd5bfd48bcfd0e77c1c0c185383a8bdb9a5db9d678

test:
  secret_key_base: 820004622998e0f6d224b491b69d1942625d1b4f9ba62f3e18b17ed1169655cf09ba1cc645ba73cc3712eeb03c394d73fa19d8f12c4083c11de36566df2d6121

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
